### ISSUE TITLE
4.1.1 Factory Bot - Sublime Text 3 inconsistency. 

### ISSUE THREAD

**Issue by DavidPerich** [rubysherpas/active_rails_examples#12]
Hey, 

```ruby
RSpec.feature "Users can view projects" do
  scenario "with the project details" do
    project = FactoryBot.create(:project, name: "Visual Studio Code")

    visit "/"
    click_link "Visual Studio Code"
    expect(page.current_url).to eq project_url(project)
  end
end
```

The code here uses `Visual Studio Code` as the `name`, but then the error code block and paragraph use `Sublime Text 3`. See below

```
1) Users can view projects with the project details
   Failure/Error: project = FactoryGirl.create(:project,
   name: "Sublime Text 3")
   ArgumentError:
     Factory not registered: project
```

> When you define the factory in this file, you give it a name attribute, so that every new project generated by the factory via FactoryGirl.create :project will have the name "Example project". The name: **"Sublime Text 3"** part of this method call in spec/features/viewing_projects_spec.rb changes .....:

**Comment by DavidPerich** [comment]
Similar issue with 4.2.1 

```ruby
require "rails_helper"

RSpec.feature "Users can edit existing projects" do
  scenario "with valid attributes" do
    FactoryGirl.create(:project, name: "Sublime Text 3")

    visit "/"
    click_link "Visual Studio Code"
    click_link "Edit Project"
    fill_in "Name", with: "VS Code"
    click_button "Update Project"

    expect(page).to have_content "Project has been updated."
    expect(page).to have_content "VS Code"
  end
end
```

- name is set to **"Sublime Text 3"**, but link is **"Visual Studio Code"** 
- also `FactoryGirl` instead of `FactoryBot` which is used elsewhere.

**Comment by TigerWolf** [comment]
Thanks. This should be fixed in the current version of the book.
