### ISSUE TITLE
Found symbol not found in PDF at Chapter 1

### ISSUE THREAD

**Issue by empeje** [rubysherpas/active_rails_examples#17]
<img width="1084" alt="Screenshot 2020-06-28 22 46 14" src="https://user-images.githubusercontent.com/11813607/85952088-3b080800-b991-11ea-8b38-9ed25ccca7dd.png">

Probably there are a lot of these errs.
---
Notes:
"This version was generated on 2020-06-02 from f66fa59e9."

**Comment by TigerWolf** [comment]
Thanks. Please check the next version of the book as this should be fixed.
