### ISSUE TITLE
Boostrap error with first introduction of navbar. Chp 6.5

### ISSUE THREAD

**Issue by albarrync** [rubysherpas/active_rails_examples#19]
This version was generated on 2020-06-02 from f66fa59e9.
p. 198 Listing 124
`<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
<div class="navbar-header">
<%= link_to "Ticketee", root_path, class: "navbar-brand" %>
<button type="button" class="navbar-toggle collapsed"
data-toggle="collapse" data-target="#collapse">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="collapse navbar-collapse" id="collapse">
<ul class="nav navbar-nav">
<li class="<%= "active" if current_page?("/") %>">
<%= link_to "Home", root_path %>
</li>
</ul>
</div>
</div>
</nav>`

I tried typing and pasting this in my application.html.erb, and the navbar is not styled correctly. The 3 line menu doesn't appear at all. After installing jquery, I can use a checkbox to collapse the menu.

I pasted it above the **container-fluid** div in my application.html.erb, even though the instructions mentioned something that didn't exist in my file.

**Comment by radar** [comment]
Hi @albarrync! Could you please put your code on GitHub and link it here? That'll help us to debug this issue.
