### ISSUE TITLE
Possible incomplete code snippet in chapter 11

### ISSUE THREAD

**Issue by lxmrc** [rubysherpas/active_rails_examples#24]
I've reached a point in chapter 11 where it says my tests should be passing and to commit my changes but this test is still failing for me:

```
  1) Users can receive notifications about ticket updates ticket authors automatically receive notifications
     Failure/Error: email = find_email!(alice.email)
     
     EmailSpec::CouldNotFindEmailError:
       Could not find email   in the mailbox for alice@example.com. 
        Found the following emails:
     
        []
```
I have:
- created the `CommentNotifier` service class
- made the changes to `CommentsController` in listing 296
- generated the comment mailer and defined the `new_comment` method
- created `new_comment.text.erb`
- added the `default_url_options` line to `config/environments/test.rb`

But I still have this failing test which appears on p. 384 and seems like it should've been resolved by creating the `CommentNotifier` service class and making the changes to `CommentsController`.

I'm wondering if the problem might be in listing 296 (p. 388): 

```ruby
class CommentsController < ApplicationController
...
  def create
    @comment = @ticket.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      comment_notifier = CommentNotifier.new(@comment)
      comment_notifier.notify_watchers
      flash[:notice] = "Comment has been created."
      redirect_to [@ticket.project, @ticket]
    else
      flash.now[:alert] = "Comment has not been created."
      @states = State.all
      @project = @ticket.project
      render "tickets/show"
    end
end
...
```

The text underneath it says:

>You can see that the creation logic in the controller has been replaced with the new service class and its `build` method. It also unwraps the comment from the service class in the error case; you need to have the actual comment to display on the comment form, not the service class.

These lines confuse me because no logic has been replaced as far as I can tell, only two lines have been added since we last saw the `#create` action in listing 252 on p. 335, and also because the service class doesn't have a `build` method. I'm also not sure what the part about unwrapping the comment is referring to.

Is there something missing from listing 296 or have I missed something?

**Comment by lxmrc** [comment]
My apologies, there was nothing missing from listing 296.

I managed to fix this by using `deliver` instead of `deliver_later`:

```ruby
  def notify_watchers
    (comment.ticket.watchers.except(comment.author)).each do |user|
      CommentMailer
        .new_comment(comment, user)
        .deliver
    end
  end
```

Based on my limited understanding of background jobs I guess the email wasn't being sent quickly enough for RSpec's liking.

**Comment by radar** [comment]
Thank you for filing this @lxmrc. It's been a while, but I've finally gotten around to reviewing this chapter and have corrected the mistake by using `perform_enqueued_jobs` in the test:

https://github.com/rubysherpas/active_rails_examples/blob/rails-61/ticketee/spec/features/ticket_notifications_spec.rb#L24
