### ISSUE TITLE
Spelling issue in https://activerailsbook.com/sample/about-this-book

### ISSUE THREAD

**Issue by casualc0der** [rubysherpas/active_rails_examples#5]
Hi Team, 

This version was generated on 2020-04-30 from 0bd951b05

Potential spelling mistake in the content at subjected URL. Suspect the word should be begin, rather than being?

Looking forward to getting started with the book :) 

This book is primarily for those who are looking to **_being_** working with the Ruby on Rails framework and who have some prior experience with Ruby, although that is not entirely necessary. The chapters get more and more advanced as you go along and provide a smooth learning curve in order to teach you how Rails applications are built.

**Comment by casualc0der** [comment]
If you’re looking for a book that teaches you the same practices that are used in the real world, then this is the book **your** are looking for.

Suspect this should be you?

**Comment by TigerWolf** [comment]
Thanks for your suggestions.
